import 'package:flutter/material.dart';

const textInputDecoration = InputDecoration(
  fillColor: Colors.white,
  filled: true,
  contentPadding: EdgeInsets.all(12.0),
  enabledBorder: OutlineInputBorder(
    borderSide: BorderSide(color: Colors.white, width: 2.0),
  ),
  focusedBorder: OutlineInputBorder(
    borderSide: BorderSide(color: Colors.pink, width: 2.0),
  ),
);

const List<String> westernStns = <String>[
  'Churchgate',
  'Marine Lines',
  'Charni Road',
  'Grant Road',
  'Mumbai Central',
  'Mahalaxmi',
  'Lower Parel',
  'Elphinstone Road',
  'Dadar',
  'Matunga Road',
  'Mahim',
  'Bandra',
  'Khar Road',
  'Santacruz',
  'Vile Parle',
  'Andheri',
  'Jogeshwari',
  'Goregaon',
  'Malad',
  'Kandivali',
  'Borivali',
  'Dahisar',
  'Mira Road',
  'Bhayandar',
  'Naigaon',
  'Vasai Road',
  'Nala Sopara',
  'Virar',
  'valtarna',
  'Saphale',
  'Kelve Road',
  'Palghar',
  'Umroli',
  'Boisar',
  'Vangaon',
  'Dahanu Road'
];
const List<String> centralStns = <String>[
  'CSMT',
  'Masjid',
  'Sandhurst Road',
  'Byculla',
  'Chinchpokli',
  'Currey Road',
  'Parel',
  'Dadar',
  'Matunga',
  'Sion',
  'Kurla',
  'Vidyavihar',
  'Ghatkopar',
  'Vikhroli',
  'Kanjurmarg',
  'Bhandhup',
  'Nahur',
  'Mulund',
  'Thane',
  'Kalwa',
  'Mumbra',
  'Diva',
  'Kopar',
  'Dombivli',
  'Thakurli',
  'Kalyan'
];
